### PR TITLE
Exporting enums for typescript compatibility.

### PR DESCRIPTION
**Pull request by centrual**
Hello,

In the current version of index.js, we can't use typescript enums in code. It is fixing this situation. It is not a very clear way to do that, but it's working.

Have a great day!

### CODE REVIEW

**Comment by iaphub** [comment]
Thanks for the PR @centrual.
Doesn't look like a clean way indeed, is having these enums necessary for the TypeScript support?

**Comment by centrual** [comment]
For the last version of the typescript declaration file, yes. But we can change enums to types or we can change the code as a typescript.

**Comment by iaphub** [comment]
Ok thanks @centrual.
We're not planning to convert the code to TypeScript but we are open to make things easy for TypeScript users.
If we don't have to modify the index.js and it'll be better for TypeScript users, your second solution  changing enums to types sounds great.

**Comment by adamnbowen** [comment]
At least for the  EIapHubEnvironment type, I think it makes more sense to use this as its type:

```typescript
export type EIapHubEnvironment = 'production' | 'staging' | 'development'
```

That at least would still provide the proper hints to people using TypeScript without requiring changes to the JavaScript.

I haven't looked into how the other enums are used yet to determine the best way to do them.

**Comment by centrual** [comment]
Hello guys,

I changed enums to types. You can check from https://github.com/iaphub/react-native-iaphub/pull/17

Have a great day!

**Pull request closed without merging**
